version: '3'
services:
    web:
        build: .
        links:
            - db
        ports:
            - "9999:8000"
        volumes:
            - .:/usr/src/es-map
        environment:
            - DATABASE_URL=mysql://root:epicbaconpassword@db/esmap
            - DEBUG
    db:
        image: mariadb:5.5
        environment:
            - MYSQL_ROOT_PASSWORD=epicbaconpassword
            - MYSQL_DATABASE=esmap